name: Matric demo
on: push
jobs:
  build:
    strategy:
      matrix: 
        node-versions: [12, 14, 16, 22]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@3
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Install Dependecies
        run: npm ci
      - name: Build project
        run: npm run build
