name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifacts files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          name: ${{ inputs.artifact-name }}
      - name: List the files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading"